apiVersion: v1
kind: Pod
metadata:
  name: insecure-privileged
  namespace: audit-zone
  labels:
    app: insecure-privileged
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
    runAsGroup: 101
    seccompProfile: {type: RuntimeDefault}
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:1.27.4-alpine
      securityContext:
        privileged: true
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities: {drop: ["ALL"]}
