apiVersion: v1
kind: Pod
metadata:
  name: insecure-root
  namespace: audit-zone
  labels:
    app: insecure-root
spec:
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    seccompProfile: {type: RuntimeDefault}
  containers:
    - name: nginx
      image: nginx:1.27.4-alpine
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities: {drop: ["ALL"]}
