apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireRestrictedContainer
metadata:
  name: require-restricted-container-settings
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["audit-zone", "gatekeeper-test"]
