apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdenyhostpath
spec:
  crd:
    spec:
      names:
        kind: K8sDenyHostPath
      validation:
        openAPIV3Schema:
          type: object
  targets:
    - target: admission.k8s.gatekeeper.sh
      code:
        - engine: Rego
          source:
            version: "v1"
            rego: |
              package k8sdenyhostpath

              violation contains {"msg": msg} if {
                volume := input.review.object.spec.volumes[_]
                volume.hostPath
                msg := sprintf("K8sDenyHostPath: том %q использует запрещённый hostPath", [volume.name])
              }
