apiVersion: v1
kind: Pod
metadata:
  name: secure-hostpath-alternative
  namespace: audit-zone
  labels:
    app: secure-hostpath-alternative
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
    runAsGroup: 101
    fsGroup: 101
    seccompProfile: {type: RuntimeDefault}
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:1.27.4-alpine
      ports: [{name: http, containerPort: 8080}]
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities: {drop: ["ALL"]}
      volumeMounts:
        - {name: cache, mountPath: /var/cache/nginx}
        - {name: run, mountPath: /var/run}
        - {name: tmp, mountPath: /tmp}
  volumes:
    - {name: cache, emptyDir: {}}
    - {name: run, emptyDir: {}}
    - {name: tmp, emptyDir: {}}
